// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa0asCg6625JSLbY2vipHLFYglGvLZj9I',
    appId: '1:435063934576:web:000248f2439c4c44802eb5',
    messagingSenderId: '435063934576',
    projectId: 'habito-a-habit-tracker',
    authDomain: 'habito-a-habit-tracker.firebaseapp.com',
    storageBucket: 'habito-a-habit-tracker.appspot.com',
    measurementId: 'G-8FE9S59YEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeTwHf8b4MZb2F_n6OMTfr7CWtSHy-1ms',
    appId: '1:435063934576:android:b48eb2bf2b8f4221802eb5',
    messagingSenderId: '435063934576',
    projectId: 'habito-a-habit-tracker',
    storageBucket: 'habito-a-habit-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCumBaZluyMLnITdVQT3IHXq9ruGJMUD5s',
    appId: '1:435063934576:ios:73cda07315757500802eb5',
    messagingSenderId: '435063934576',
    projectId: 'habito-a-habit-tracker',
    storageBucket: 'habito-a-habit-tracker.appspot.com',
    iosClientId:
        '435063934576-h7g36hjcmn58ujr7ad5g1neoeu2iamoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.habito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCumBaZluyMLnITdVQT3IHXq9ruGJMUD5s',
    appId: '1:435063934576:ios:73cda07315757500802eb5',
    messagingSenderId: '435063934576',
    projectId: 'habito-a-habit-tracker',
    storageBucket: 'habito-a-habit-tracker.appspot.com',
    iosClientId:
        '435063934576-h7g36hjcmn58ujr7ad5g1neoeu2iamoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.habito',
  );
}
